// Code generated by protoc-gen-go. DO NOT EDIT.
// source: OK.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	OK.proto
	PlayerInfo.proto
	Rqst_CreateSelf.proto
	Rqst_HeartBeating.proto
	Rqst_UpdateStatus.proto
	Rqst_UpdateStatus_Confirm.proto
	Rspn_CreateOthers.proto
	Rspn_CreateSelf.proto
	Rspn_HeartBeating.proto
	Rspn_LeaveOffOthers.proto
	Rspn_StatusUpdateExitGame.proto
	Rspn_StatusUpdateJump.proto
	Rspn_StatusUpdateMove.proto
	Rspn_StatusUpdateSprint.proto
	Rspn_StatusUpdateTabSwitch.proto
	Rspn_UpdateStatus.proto
	helloworld.proto

It has these top-level messages:
	OK
	StatusInfo
	PlayerInfo
	Vect3
	Rqst_CreateSelf
	Rqst_HeartBeating
	Rqst_UpdateStatus
	Rqst_UpdateStatus_Confirm
	Rspn_CreateOthers
	Rspn_CreateSelf
	Rspn_HeartBeating
	Rspn_LeaveOffOthers
	Rspn_StatusUpdateExitGame
	Rspn_StatusUpdateJump
	Rspn_StatusUpdateMove
	Rspn_StatusUpdateSprint
	Rspn_StatusUpdateTabSwitch
	Rspn_UpdateStatus
	Helloworld
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OK struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OK) Reset()                    { *m = OK{} }
func (m *OK) String() string            { return proto.CompactTextString(m) }
func (*OK) ProtoMessage()               {}
func (*OK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OK) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*OK)(nil), "msg.OK")
}

func init() { proto.RegisterFile("OK.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 57 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf0, 0xf7, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x12, 0xe0, 0x62, 0xf2, 0xf7, 0x16,
	0xe2, 0xe2, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x05, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xc6, 0x10, 0x1a, 0x1b, 0x21, 0x00, 0x00, 0x00,
}
