// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Rqst_CreateSelf.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Rqst_CreateSelf struct {
	Account          *string `protobuf:"bytes,1,req,name=Account" json:"Account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=Password" json:"Password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Rqst_CreateSelf) Reset()                    { *m = Rqst_CreateSelf{} }
func (m *Rqst_CreateSelf) String() string            { return proto.CompactTextString(m) }
func (*Rqst_CreateSelf) ProtoMessage()               {}
func (*Rqst_CreateSelf) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Rqst_CreateSelf) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Rqst_CreateSelf) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Rqst_CreateSelf)(nil), "msg.Rqst_CreateSelf")
}

func init() { proto.RegisterFile("Rqst_CreateSelf.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0d, 0x2a, 0x2c, 0x2e,
	0x89, 0x77, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4e, 0xcd, 0x49, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x32, 0xe1, 0xe2, 0x47, 0x93, 0x15, 0xe2, 0xe7, 0x62,
	0x77, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x14, 0x12, 0xe0,
	0xe2, 0x08, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x02, 0x89, 0x00, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0x09, 0xb9, 0x62, 0x52, 0x00, 0x00, 0x00,
}
