// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Rqst_UpdateStatus_Confirm.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Rqst_UpdateStatus_Confirm struct {
	FrameID          *int64  `protobuf:"varint,1,req,name=FrameID" json:"FrameID,omitempty"`
	UserID           *string `protobuf:"bytes,2,req,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Rqst_UpdateStatus_Confirm) Reset()                    { *m = Rqst_UpdateStatus_Confirm{} }
func (m *Rqst_UpdateStatus_Confirm) String() string            { return proto.CompactTextString(m) }
func (*Rqst_UpdateStatus_Confirm) ProtoMessage()               {}
func (*Rqst_UpdateStatus_Confirm) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Rqst_UpdateStatus_Confirm) GetFrameID() int64 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

func (m *Rqst_UpdateStatus_Confirm) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Rqst_UpdateStatus_Confirm)(nil), "msg.Rqst_UpdateStatus_Confirm")
}

func init() { proto.RegisterFile("Rqst_UpdateStatus_Confirm.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0f, 0x2a, 0x2c, 0x2e,
	0x89, 0x0f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x0d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x8e, 0x77, 0xce,
	0xcf, 0x4b, 0xcb, 0x2c, 0xca, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e,
	0x57, 0xb2, 0xe1, 0x92, 0xc4, 0xa9, 0x4e, 0x88, 0x9f, 0x8b, 0xdd, 0xad, 0x28, 0x31, 0x37, 0xd5,
	0xd3, 0x45, 0x82, 0x51, 0x81, 0x49, 0x83, 0x59, 0x88, 0x8f, 0x8b, 0x2d, 0xb4, 0x38, 0xb5, 0xc8,
	0xd3, 0x45, 0x82, 0x49, 0x81, 0x49, 0x83, 0x13, 0x10, 0x00, 0x00, 0xff, 0xff, 0x25, 0xab, 0xf6,
	0x29, 0x64, 0x00, 0x00, 0x00,
}
